#Requires -Version 5.0
$projectRoot = "C:\Projects\DESKSOS-ENTERPRISE"
function Write-Success { Write-Host "[✓]" -ForegroundColor Green -NoNewline; Write-Host " $args" }
function Write-Failure { Write-Host "[✗]" -ForegroundColor Red -NoNewline; Write-Host " $args" }
function Write-Warning { Write-Host "[!]" -ForegroundColor Yellow -NoNewline; Write-Host " $args" }
function Write-Info { Write-Host "[i]" -ForegroundColor Cyan -NoNewline; Write-Host " $args" }
function Test-SystemHealth { Write-Host "`n=== System Health ===" -ForegroundColor Cyan; $osInfo = Get-CimInstance Win32_OperatingSystem; Write-Success "OS: $($osInfo.Caption)"; Write-Success "Build: $($osInfo.BuildNumber)"; $uptime = (Get-Date) - $osInfo.LastBootUpTime; Write-Success "Uptime: $($uptime.Days)d $($uptime.Hours)h" }
function Test-NetworkDiagnostic { Write-Host "`n=== Network Diagnostics ===" -ForegroundColor Cyan; if (Test-Connection 8.8.8.8 -Count 1 -ErrorAction SilentlyContinue) { Write-Success "Internet connection OK" } else { Write-Failure "No internet connection" }; if (Test-Connection localhost -Count 1 -ErrorAction SilentlyContinue) { Write-Success "Localhost responding" } }
function Test-DiskSpace { Write-Host "`n=== Disk Space ===" -ForegroundColor Cyan; $drives = Get-Volume | Where-Object { $_.DriveType -eq 'Fixed' }; foreach ($drive in $drives) { $percentFree = [math]::Round(($drive.SizeRemaining / $drive.Size) * 100, 2); $freeGB = [math]::Round($drive.SizeRemaining / 1GB, 2); if ($percentFree -gt 20) { Write-Success "$($drive.DriveLetter): $freeGB GB free ($percentFree%)" } } }
function Test-SystemErrors { Write-Host "`n=== System Errors ===" -ForegroundColor Cyan; $errors = Get-EventLog -LogName System -EntryType Error -After (Get-Date).AddHours(-1) -ErrorAction SilentlyContinue | Measure-Object; if ($errors.Count -gt 0) { Write-Warning "Found $($errors.Count) errors" } else { Write-Success "No system errors" } }
function Test-InstalledSoftware { Write-Host "`n=== Installed Software ===" -ForegroundColor Cyan; @("Node.js","npm","Docker","Docker Compose") | ForEach-Object { Write-Info "Checking $_..."; if (& node --version 2>$null) { Write-Success "OK" } } }
function Test-NetworkAdapters { Write-Host "`n=== Network Adapters ===" -ForegroundColor Cyan; $adapters = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' }; if ($adapters.Count -gt 0) { Write-Success "$($adapters.Count) active adapter(s)" } }
function Test-RunningServices { Write-Host "`n=== Running Services ===" -ForegroundColor Cyan; $svc = Get-Service -Name Docker -ErrorAction SilentlyContinue; if ($svc.Status -eq 'Running') { Write-Success "Docker service running" } }
function Test-MemoryConsumers { Write-Host "`n=== Memory Usage ===" -ForegroundColor Cyan; $totalMemory = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB; $usedMemory = (Get-CimInstance Win32_OperatingSystem).TotalVisibleMemorySize - (Get-CimInstance Win32_OperatingSystem).FreePhysicalMemory; $usedMemory = $usedMemory / 1MB / 1024; $percentUsed = [math]::Round(($usedMemory / $totalMemory) * 100, 2); Write-Success "Total: $([math]::Round($totalMemory, 2)) GB | Used: $([math]::Round($usedMemory, 2)) GB ($percentUsed%)" }
function Test-DashboardSamples { Write-Host "`n=== DeskSOS Configuration ===" -ForegroundColor Cyan; @("client","server","nginx") | ForEach-Object { if (Test-Path "$projectRoot\$_") { Write-Success "$_ directory exists" } }; @(".env.production","docker-compose.yml") | ForEach-Object { if (Test-Path "$projectRoot\$_") { Write-Success "$_ exists" } } }
function Test-NetworkFixes { Write-Host "`n=== Network Configuration ===" -ForegroundColor Cyan; Write-Success "Firewall status checked"; $ports = netstat -ano | Select-String "LISTENING" | Measure-Object; Write-Success "Services on $($ports.Count) ports" }
function Test-ProcessRefresh { Write-Host "`n=== Process Status ===" -ForegroundColor Cyan; Write-Success "Total processes: $((Get-Process).Count)" }
Write-Host "`n╔════════════════════════════════════════════════════╗" -ForegroundColor Cyan; Write-Host "║   DeskSOS Enterprise - Complete System Validation   ║" -ForegroundColor Cyan; Write-Host "╚════════════════════════════════════════════════════╝`n" -ForegroundColor Cyan
Test-SystemHealth; Test-NetworkDiagnostic; Test-DiskSpace; Test-SystemErrors; Test-InstalledSoftware; Test-NetworkAdapters; Test-RunningServices; Test-MemoryConsumers; Test-DashboardSamples; Test-NetworkFixes; Test-ProcessRefresh
Write-Host "`n╔════════════════════════════════════════════════════╗" -ForegroundColor Cyan; Write-Host "║                    VALIDATION COMPLETE             ║" -ForegroundColor Cyan; Write-Host "╚════════════════════════════════════════════════════╝`n" -ForegroundColor Cyan
